ALTER TABLE users
CHANGE COLUMN UserID user_id INT NOT NULL AUTO_INCREMENT,
CHANGE COLUMN Username username VARCHAR(200) NOT NULL,
CHANGE COLUMN PasswordHash password_hash VARCHAR(200) NOT NULL;

ALTER TABLE account_data
CHANGE COLUMN UserID user_id INT NOT NULL,
CHANGE COLUMN SessionData session_data MEDIUMTEXT;
